### ISSUE TITLE
Error when preprocessing dataset

### ISSUE THREAD

**Issue by aliencaocao** [THUcqb/KOBE#49]
I am following the readme file instruction to download and preprocess the provided data, however I am stuck on the preprocess step.
I am trying to run `python -m kobe.data.vocab --input saved/raw/train.cond --vocab-file saved/vocab.cond --vocab-size 31 --algo word`

```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\alien\Documents\PyCharm-Projects\KOBE\kobe\data\vocab.py", line 35, in <module>
    spm.SentencePieceTrainer.Train(
  File "C:\Program Files\Python39\lib\site-packages\sentencepiece\__init__.py", line 407, in Train
    return SentencePieceTrainer._TrainFromString(arg)
  File "C:\Program Files\Python39\lib\site-packages\sentencepiece\__init__.py", line 385, in _TrainFromString
    return _sentencepiece.SentencePieceTrainer__TrainFromString(arg)
OSError: Not found: "C:\Users\alien\AppData\Local\Temp\tmpxplscd17": Permission denied Error #13
```

I have checked the folder's permission is fully accessible to my account, and I am already running cmd as admin.

**Comment by qibinc** [comment]
Hi @aliencaocao ,

Please check out the prerequisite https://github.com/THUDM/KOBE#prerequisites. Windows is currently not support. Besides, we suggest that tuning the number  `--vocab-size 31` according to the number of attributes on your dataset might be helpful for performance improvement.
